### ISSUE TITLE
time.ParseDuration() does not allow `d`ays (`auto-vacuum-int`)

### ISSUE THREAD

**Issue by axllent** [rqlite/rqlite.io#14]
In [the docs](https://github.com/rqlite/rqlite.io/blob/3e3b1786c826befc6ba4289a32c9c274e1876125/content/en/docs/Guides/Performance/_index.md?plain=1#L35) it describes `rqlited -auto-vacuum-int=14d`, however the flag that handles that does not actually cater for days (`invalid value "14d" for flag -auto-vacuum-int: parse error`). As far as I'm aware, the only valid units of time measure supported are `s`, `m`, and `h`.

So 14 days would be `-auto-vacuum-int=336h` :+1:

**Comment by otoolep** [comment]
You are absolutely right -- thank you.

https://pkg.go.dev/time#ParseDuration
